from .amazon import amazon
from .avito import avito
from .dodopizza import dodopizza
from .kaspi import kaspi
from .kufar import kufar
from .magnit import magnit
from .olx import olx
from .ozon import ozon
from .vinted import vinted
from .wildberries import wildberries
from .allegro import allegro
from .wallapop import wallapop